- Assets/Xbox Live/Scripts/GameSave.meta
- Assets/Xbox Live/Scripts/GameSave/GameSave.unitypackage.meta
- Assets/Xbox Live/Scripts/GameSave/GameSaveHelper.cs
- Assets/Xbox Live/Scripts/GameSave/GameSaveHelper.cs.meta
- Assets/Xbox Live/Scripts/GameSave/GameSaveStatus.cs
- Assets/Xbox Live/Scripts/GameSave/GameSaveStatus.cs.meta
- Assets/Xbox Live/Scripts/GameSave/GameSaveUI.cs
- Assets/Xbox Live/Scripts/GameSave/GameSaveUI.cs.meta
- Assets/Xbox Live/Scripts/GameSave/StorageContainerInfo.cs
- Assets/Xbox Live/Scripts/GameSave/StorageContainerInfo.cs.meta
- Assets/Xbox Live/Scripts/GameSave/StorageContainerQueryResult.cs
- Assets/Xbox Live/Scripts/GameSave/StorageContainerQueryResult.cs.meta
- Build/BuildPackage.ps1
- Added Scripts that surface GameSaves in Unity
- Added the generation of the GameSave Plugin within BuildScript.ps1
> GameSavePlugin Scripts and Packaging

- Assets/Xbox Live/GameSave/Examples/GameSaveExample.unity
- Assets/Xbox Live/GameSave/Examples/GameSaveExample.unity.meta
- Assets/Xbox Live/GameSave/GameSave.unitypackage.meta
- Assets/Xbox Live/GameSave/Prefabs/GameSaveUI.prefab
- Assets/Xbox Live/GameSave/Prefabs/GameSaveUI.prefab.meta
- Assets/Xbox Live/GameSave/Scripts/GameSaveHelper.cs.meta
- Assets/Xbox Live/GameSave/Scripts/GameSaveStatus.cs.meta
- Assets/Xbox Live/GameSave/Scripts/GameSaveUI.cs.meta
- Build/BuildPackage.ps1
- Added an Example Scene for GameSave
- Fixed a Game Save Prefab bug
> Adding game save example

- Assets/Xbox Live/GameSave/Scripts/GameSaveHelper.cs
- Assets/Xbox Live/GameSave/Scripts/GameSaveStatus.cs
- Assets/Xbox Live/GameSave/Scripts/GameSaveUI.cs
- Assets/Xbox Live/GameSave/Scripts/StorageContainerInfo.cs
- Assets/Xbox Live/GameSave/Scripts/StorageContainerQueryResult.cs
- Assets/Xbox Live/Scripts/Leaderboard.cs
- Assets/Xbox Live/Scripts/XboxLiveUserInfo.cs
- Assets/Xbox Live/Scripts/XboxLiveUserManager.cs
> Fixing Leaderboard bug

- Assets/Xbox Live/Examples/MultiUserExample/MultiUser.unity
- Assets/Xbox Live/GameSave/README.txt.meta
- Assets/Xbox Live/Prefabs/UserProfile.prefab
> Fixing Bug in User Profile

- Assets/Xbox Live/Scripts/Social.cs
Renaming Friendly Name of All Online Filter
> Changing the friendly name of the All Online Filter

- Assets/Xbox Live/Prefabs/Social.prefab
Changing UI setting for Social Prefab to resize correctly
> Changing UI setting for Social Prefab to resize correctly

- Assets/Xbox Live/Scripts/UserProfile.cs
- Sign In happen automatically when in Single user mode
> SignIn happen automatically when in Single user mode

- Assets/Xbox Live/GameSave/Prefabs/GameSaveUI.prefab
- Assets/Xbox Live/GameSave/Prefabs/GameSaveUI.prefab.meta
- Assets/Xbox Live/GameSave/Scripts/GameSaveUI.cs
- Assets/Xbox Live/Scripts/Leaderboard.cs
- Assets/Xbox Live/Scripts/Social.cs
- Assets/Xbox Live/Scripts/UserProfile.cs
- Added Controller Support to the different Xbox Live Prefabs
- Fixed a minor bug in Leaderboard Prefab
> Controller support

- Assets/Xbox Live/Scripts/UserProfile.cs
Fixing a bug in UserProfile.cs that was causing exceptions when the game is offline.
> Fixing a bug in UserProfile.cs 

- Assets/Xbox Live/Scripts/UserProfile.cs
- Assets/Xbox Live/Scripts/XboxLiveUserInfo.cs
Fixing Persistence Issue in UserProfile
> Fix sign in persistence issue

- Assets/Xbox Live/Scripts/Leaderboard.cs
Fixing an issue in Leaderboards Prefab behavior across scenes
> Fixing an issue in Leaderboards Prefab behavior across scenes

- Assets/Xbox Live/GameSave/Scripts/GameSaveHelper.cs
- Assets/Xbox Live/GameSave/Scripts/GameSaveUI.cs
- Assets/Xbox Live/Scripts/Leaderboard.cs
- Assets/Xbox Live/Scripts/Social.cs
- Assets/Xbox Live/Scripts/Stats/StatBase.cs
- Assets/Xbox Live/Scripts/Stats/StatPanel.cs
- Assets/Xbox Live/Scripts/UserProfile.cs
- Assets/Xbox Live/Scripts/XboxLiveServicesSettings.cs
- Assets/Xbox Live/Scripts/XboxLiveUserInfo.cs
- Updating directives being used to enable future IL2CPP support
- Fixed a bug in GameSaveHelper
> Updating directives being used to enable future IL2CPP support

- Assets/Xbox Live/Scripts/UserProfile.cs
- CSharpSource/Source/api/Common/XboxLive.cs
- CSharpSource/Source/api/Microsoft.Xbox.Services.Shared.projitems
- CSharpSource/Source/api/Presence/IPresenceWriter.cs
- CSharpSource/Source/api/Presence/MediaPresenceData.cs
- CSharpSource/Source/api/Presence/MockPresenceWriter.cs
- CSharpSource/Source/api/Presence/PresenceActivityData.cs
- CSharpSource/Source/api/Presence/PresenceData.cs
- CSharpSource/Source/api/Presence/PresenceRequest.cs
- CSharpSource/Source/api/Presence/PresenceWriter.cs
- CSharpSource/Source/api/Presence/SimplePresenceRequest.cs
- CSharpSource/Source/api/Presence/UserPresenceWriterStatus.cs
> Adding Presence Writer

- Assets/Xbox Live/Scripts/Social.cs
- Assets/Xbox Live/Scripts/Stats/StatBase.cs
Fixing a bug in Social and Stats prefabs between scenes
> Fixing a bug in Social and Stats prefabs between scenes

- CSharpSource/Source/Microsoft.Xbox.Services.UWP.CSharp/Social/Manager/SocialEvent.cs
- CSharpSource/Source/Microsoft.Xbox.Services.UWP.CSharp/Social/Manager/SocialManager.cs
- CSharpSource/Source/Microsoft.Xbox.Services.UWP.CSharp/Social/Manager/XboxSocialUserGroup.cs
- CSharpSource/Source/Microsoft.Xbox.Services.UWP.CSharp/Statistics/Manager/StatisticManager.cs
- CSharpSource/Source/api/Leaderboard/LeaderboardResult.cs
- CSharpSource/Source/api/Leaderboard/LeaderboardRow.cs
- CSharpSource/Source/api/Social/Manager/SocialManagerPresenceRecord.cs
- CSharpSource/Tests/IntegrationTests/UWP/UWPIntegration/MainPage.xaml.cs
- CSharpSource/Tests/IntegrationTests/UWP/UWPIntegration/UWPIntegration.csproj
- CppSource/Include/xsapi/leaderboard_c.h
- CppSource/Include/xsapi/social_manager_c.h
- CppSource/Include/xsapi/stats_manager_c.h
- CppSource/Source/Leaderboard/leaderboard_helper_c.cpp
- CppSource/Source/Social/Manager/social_manager_c.cpp
- CppSource/Source/Social/Manager/social_manager_helper_c.cpp
- CppSource/Source/Stats/Manager/stats_manager_c.cpp
Fixes runtime errors and clears build warnings
> Changed how SocialManager and StatisticManager marshal size_t

- Assets/Xbox Live/Scripts/UserProfile.cs
- Assets/Xbox Live/Scripts/XboxLiveUserInfo.cs
- CSharpSource/Source/Microsoft.Xbox.Services.UnityEditor.CSharp/Microsoft.Xbox.Services.UnityEditor.CSharp.csproj
Clean up UserProfile and XboxLiveUser scripts. Fixes issue with MUA sign in.
> Fix bug in MUA SignIn flow

- Assets/Xbox Live/Scripts/Leaderboard.cs
- Assets/Xbox Live/Scripts/LeaderboardEntry.cs
Displayed gamerpics in the leaderboard prefab and fixed leaderboard prefab page rendering
> Leaderboard prefab fixes

- Assets/Xbox Live/Scripts/UserProfile.cs
- Build/InstallXboxLiveSdk.ps1
Signin button didn't get disabled during initial sign in attempt.
Also change setup script to build both .NET 3.5 and .NET 4.5 configurations.
> Fixing bug in UserProfile 

- Assets/Xbox Live/Editor/XboxLivePostProcessing.cs
- CSharpSource/Source/api/Privacy/IPrivacyService.cs
- CSharpSource/Source/api/Privacy/MultiplePermissionsCheckResult.cs
- CSharpSource/Source/api/Privacy/PermissionCheckResult.cs
- CSharpSource/Source/api/Privacy/PrivacyService.cs
- CSharpSource/Source/api/Social/ProfileService.cs
- CSharpSource/Source/api/System/MarshallingHelpers.cs
- CSharpSource/Source/api/TitleStorage/ITitleStorageService.cs
- CSharpSource/Source/api/TitleStorage/TitleStorageBlobMetadata.cs
- CSharpSource/Source/api/TitleStorage/TitleStorageService.cs
* updating the unity project post processing script
* fixing .NET compat issues
> Fixing some .NET version compatibility issues

- Utilities/VSOBuildScripts/postBuildScript.cmd
* Post build script was previously updated in release branches and never properly merged back to master
* Removes some unneeded copying and changes to clearer variable names
> Fixing post build script

- Assets/Xbox Live/Scripts/UserProfile.cs
Properly handle cancelling user selection for MUA in UserPicker.
> Improve the error handling in UserProfile prefab. 

- Assets/Xbox Live/GameSave/Scripts/GameSaveHelper.cs
* Fixing broken namespaces in GameSave
> Fixing a bug in namespace handling in GameSave

- Assets/Xbox Live/GameSave/Examples/GameSaveExample.unity
- Assets/Xbox Live/Scripts/FilterSelect.cs
Fixing GameSave Example bug and Filter select color bug
> Fixing GameSave Example bug and Filter select color bug

- Assets/Xbox Live/Scripts/PlayerAuthentication.cs
- Assets/Xbox Live/Scripts/SignInManager.cs
- Assets/Xbox Live/Scripts/XboxLiveAuthStatus.cs
> Fixing Canceled Sign In Bug

- README.md
It was CONTRIBUTING.MD, but it should be CONTRIBUTING.md
> Fix incorrrect link for CONTRIBUTING.md in readme

- README.md
Updating Readme with 2021 updates
> Updating Readme with 2021 updates
